name: Build and Draft Release

on:
  workflow_dispatch:
  push:
    branches: main
    paths: ["src/**", "io.baumert.vmix.sdPlugin/**"]

jobs:
  read-version:
    name: Read version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version
        id: version
        shell: bash
        run: echo VERSION=$(cat io.baumert.vmix.sdPlugin/manifest.json | jq -r '.Version') >> $GITHUB_OUTPUT

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [read-version]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog_config.json"

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: v${{needs.read-version.outputs.version}}
          body: ${{steps.build-changelog.outputs.changelog}}

  build-upload:
    name: "Build & Upload"
    needs: [create-release, read-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install Maker CLI
        run: npm install -g @elgato/cli

      - name: Install Project Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Update manifest.json debug
        uses: jossef/action-set-json-field@v2.1
        with:
          file: io.baumert.vmix.sdPlugin/manifest.json
          field: Nodejs.Debug
          value: undefined

      - name: Pack
        run: streamdeck pack io.baumert.vmix.sdPlugin --version ${{needs.read-version.outputs.version}}

      - name: Rename Binary
        run: mv io.baumert.vmix.streamDeckPlugin io.baumert.vmix-${{needs.read-version.outputs.version}}.streamDeckPlugin

      - name: upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: v${{needs.read-version.outputs.version}}
          files: |
            *.streamDeckPlugin
